"""cs2toUE-Setup.exe - the one and only installer.

The whole application is packed inside this file. It asks for a folder, copies the
program there, makes the shortcuts and registers an uninstall entry, all per user and
without administrator rights.

    cs2toUE-Setup.exe                       window
    cs2toUE-Setup.exe --silent [--target D:\\path] [--no-shortcuts]
"""

import os
import shutil
import subprocess
import sys
import winreg
from pathlib import Path

APP = "cs2toUE"
VERSION = "1.0.6"
REG_UNINSTALL = r"Software\Microsoft\Windows\CurrentVersion\Uninstall\cs2toUE"


def payload_dir() -> Path:
    """The bundled copy of the application."""
    base = Path(getattr(sys, "_MEIPASS", Path(__file__).resolve().parent))
    for candidate in (base / "app", base / "dist" / APP):
        if (candidate / "cs2toUE.exe").is_file():
            return candidate
    return base / "app"


def default_target() -> Path:
    """The usual place for a per-user Windows program: %LOCALAPPDATA%\\Programs\\cs2toUE.

    Not C:\\Program Files, because that folder needs administrator rights - and the
    program keeps its workspace (HLAE builds, converted maps, exported scenes) next to
    itself, so it has to be able to write there. The folder is a free choice in the
    installer, and any drive works.
    """
    local = os.environ.get("LOCALAPPDATA")
    if local:
        return Path(local) / "Programs" / APP
    return Path(os.environ.get("ProgramFiles", "C:\\Program Files")) / APP


def free_gb(path) -> float:
    try:
        return shutil.disk_usage(Path(path).drive + "\\").free / 1024 ** 3
    except OSError:
        return -1.0


def payload_size(src: Path) -> int:
    return sum(p.stat().st_size for p in src.rglob("*") if p.is_file())


# ------------------------------------------------------------------ install

def copy_app(src: Path, dest: Path, progress=None) -> None:
    files = [p for p in src.rglob("*") if p.is_file()]
    dest.mkdir(parents=True, exist_ok=True)
    for i, item in enumerate(files, 1):
        target = dest / item.relative_to(src)
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(item, target)
        if progress and (i % 20 == 0 or i == len(files)):
            progress(i / len(files), item.name)


def _powershell(script: str) -> None:
    """Run a script through a file, never through -Command.

    A command line with non-ASCII characters goes through the console code page of the
    machine, which turns Cyrillic into mojibake on a differently localised Windows. A
    UTF-8 file with a BOM is read correctly by PowerShell everywhere.
    """
    tmp = Path(os.environ.get("TEMP", ".")) / "cs2toue_setup_step.ps1"
    try:
        tmp.write_text(script, encoding="utf-8-sig")
        subprocess.run(["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass",
                        "-File", str(tmp)],
                       creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0), check=False)
    except Exception:
        pass
    finally:
        try:
            tmp.unlink()
        except OSError:
            pass


def make_shortcut(link: Path, target: Path, workdir: Path, description: str) -> None:
    link.parent.mkdir(parents=True, exist_ok=True)
    script = (
        "$s=(New-Object -ComObject WScript.Shell).CreateShortcut('{}');"
        "$s.TargetPath='{}';$s.WorkingDirectory='{}';$s.Description='{}';$s.Save()".format(
            link, target, workdir, description)
    )
    _powershell(script)


def create_shortcuts(dest: Path, desktop: bool = True, start_menu: bool = True) -> None:
    exe = dest / "cs2toUE.exe"
    if start_menu:
        group = Path(os.environ["APPDATA"]) / r"Microsoft\Windows\Start Menu\Programs" / APP
        make_shortcut(group / f"{APP}.lnk", exe, dest, "CS2 demo to Unreal Engine")
        make_shortcut(group / "РЈРґР°Р»РёС‚СЊ cs2toUE.lnk", dest / "Uninstall.cmd", dest,
                      "Uninstall cs2toUE")
    if desktop:
        desk = Path(os.path.expanduser("~")) / "Desktop"
        if not desk.is_dir():
            desk = Path(os.environ.get("USERPROFILE", ".")) / "Desktop"
        make_shortcut(desk / f"{APP}.lnk", exe, dest, "CS2 demo to Unreal Engine")


UNINSTALL_CMD = """@echo off
rem Removes cs2toUE. Generated by the installer.
echo Removing cs2toUE from "{dest}"
echo.
reg delete "HKCU\\{reg}" /f >nul 2>&1
del /q "%APPDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\{app}\\*.lnk" >nul 2>&1
rmdir "%APPDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\{app}" >nul 2>&1
del /q "%USERPROFILE%\\Desktop\\{app}.lnk" >nul 2>&1
echo The workspace folder is NOT deleted automatically - it holds the HLAE builds,
echo converted maps and exported scenes you may still want:
echo     "{dest}\\workspace"
echo.
echo Delete the program folder by hand to finish.
pause
"""


def write_uninstaller(dest: Path) -> None:
    (dest / "Uninstall.cmd").write_text(
        UNINSTALL_CMD.format(dest=dest, reg=REG_UNINSTALL, app=APP), encoding="utf-8")


def register(dest: Path, size_kb: int) -> None:
    with winreg.CreateKey(winreg.HKEY_CURRENT_USER, REG_UNINSTALL) as key:
        values = {
            "DisplayName": f"{APP} - CS2 demo to Unreal Engine",
            "DisplayVersion": VERSION,
            "Publisher": APP,
            "InstallLocation": str(dest),
            "DisplayIcon": str(dest / "cs2toUE.exe"),
            "UninstallString": f'"{dest / "Uninstall.cmd"}"',
        }
        for name, value in values.items():
            winreg.SetValueEx(key, name, 0, winreg.REG_SZ, value)
        winreg.SetValueEx(key, "EstimatedSize", 0, winreg.REG_DWORD, size_kb)
        winreg.SetValueEx(key, "NoModify", 0, winreg.REG_DWORD, 1)
        winreg.SetValueEx(key, "NoRepair", 0, winreg.REG_DWORD, 1)


def download_tools(dest: Path, status=None, timeout: int = 900) -> bool:
    """Pull HLAE and the Source 2 Viewer CLI right away.

    They are not baked into the installer on purpose: the right HLAE build depends on
    which CS2 patch the machine has, and both tools get new releases constantly. Doing
    it here means the program is complete once the installer finishes.
    """
    exe = dest / "cs2toue-cli.exe"
    if not exe.is_file():
        return False
    try:
        proc = subprocess.Popen(
            [str(exe), "prefetch"], cwd=str(dest),
            stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
            text=True, encoding="utf-8", errors="replace",
            creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
        )
    except OSError:
        return False
    try:
        for line in proc.stdout:
            line = line.strip()
            if line and status:
                status(line[:90])
        proc.wait(timeout=timeout)
    except Exception:
        proc.kill()
        return False
    return proc.returncode == 0


def install(target, desktop=True, start_menu=True, progress=None):
    src = payload_dir()
    if not (src / "cs2toUE.exe").is_file():
        raise RuntimeError(f"the installer payload is missing ({src})")
    dest = Path(target)
    need = payload_size(src)
    have = free_gb(dest)
    # half a gigabyte of headroom: HLAE, maps and exported scenes land next to the program
    if 0 <= have < (need / 1024 ** 3 + 0.5):
        raise RuntimeError(
            f"РќР° РґРёСЃРєРµ {dest.drive} РЅРµРґРѕСЃС‚Р°С‚РѕС‡РЅРѕ РјРµСЃС‚Р°: СЃРІРѕР±РѕРґРЅРѕ {have:.1f} Р“Р‘, "
            f"РЅСѓР¶РЅРѕ {need / 1024 ** 2:.0f} РњР‘ РЅР° РїСЂРѕРіСЂР°РјРјСѓ Рё Р·Р°РїР°СЃ РїРѕРґ СЃРєР°С‡РёРІР°РµРјС‹Рµ С„Р°Р№Р»С‹.\n\n"
            f"Р’С‹Р±РµСЂРёС‚Рµ РґСЂСѓРіСѓСЋ РїР°РїРєСѓ вЂ” РїРѕРґРѕР№РґС‘С‚ Р»СЋР±РѕР№ РґРёСЃРє."
        )
    copy_app(src, dest, progress)
    write_uninstaller(dest)
    if desktop or start_menu:
        create_shortcuts(dest, desktop, start_menu)
    register(dest, int(need / 1024))
    return dest


# ------------------------------------------------------------------ window

def run_gui():
    import tkinter as tk
    from tkinter import filedialog, messagebox, ttk

    root = tk.Tk()
    root.title(f"РЈСЃС‚Р°РЅРѕРІРєР° {APP} {VERSION}")
    # the size is computed from the content at the end of this function: a fixed height
    # cut the buttons off as soon as one more option was added

    ttk.Label(root, text=f"{APP} вЂ” РєРѕРЅРІРµСЂС‚РµСЂ РґРµРјРѕРє CS2 РІ Unreal Engine",
              font=("Segoe UI", 12, "bold")).pack(anchor="w", padx=16, pady=(16, 2))
    ttk.Label(root, text="Python Рё РІСЃС‘ РѕСЃС‚Р°Р»СЊРЅРѕРµ СѓР¶Рµ РІРЅСѓС‚СЂРё. РџСЂР°РІР° Р°РґРјРёРЅРёСЃС‚СЂР°С‚РѕСЂР° РЅРµ РЅСѓР¶РЅС‹.\n"
                         "HLAE, РєР°СЂС‚С‹ Рё РјРѕРґРµР»Рё СЃРєР°С‡РёРІР°СЋС‚СЃСЏ РІ РїР°РїРєСѓ РїСЂРѕРіСЂР°РјРјС‹ вЂ” РїРѕРґ РЅРёС… РјРѕР¶РµС‚\n"
                         "СѓР№С‚Рё РЅРµСЃРєРѕР»СЊРєРѕ РіРёРіР°Р±Р°Р№С‚, РїР°РїРєСѓ РјРѕР¶РЅРѕ РїРѕРјРµРЅСЏС‚СЊ РЅР° Р»СЋР±РѕР№ РґРёСЃРє.",
              justify="left").pack(anchor="w", padx=16)

    frame = ttk.Frame(root)
    frame.pack(fill="x", padx=16, pady=14)
    ttk.Label(frame, text="РџР°РїРєР° СѓСЃС‚Р°РЅРѕРІРєРё").pack(anchor="w")
    row = ttk.Frame(frame)
    row.pack(fill="x", pady=4)
    target_var = tk.StringVar(value=str(default_target()))
    entry = ttk.Entry(row, textvariable=target_var)
    entry.pack(side="left", fill="x", expand=True)

    def browse():
        chosen = filedialog.askdirectory(title="РљСѓРґР° СѓСЃС‚Р°РЅРѕРІРёС‚СЊ cs2toUE")
        if chosen:
            target_var.set(str(Path(chosen) / APP))
    ttk.Button(row, text="РћР±Р·РѕСЂ...", command=browse).pack(side="left", padx=6)

    space_var = tk.StringVar()

    def refresh_space(*_a):
        gb = free_gb(target_var.get())
        need = payload_size(payload_dir()) / 1024 ** 2
        space_var.set(f"РќСѓР¶РЅРѕ ~{need:.0f} РњР‘, СЃРІРѕР±РѕРґРЅРѕ {gb:.1f} Р“Р‘"
                      if gb >= 0 else f"РќСѓР¶РЅРѕ ~{need:.0f} РњР‘")
    target_var.trace_add("write", refresh_space)
    refresh_space()
    ttk.Label(frame, textvariable=space_var).pack(anchor="w")

    desktop_var = tk.BooleanVar(value=True)
    menu_var = tk.BooleanVar(value=True)
    tools_var = tk.BooleanVar(value=True)
    launch_var = tk.BooleanVar(value=True)
    opts = ttk.Frame(root)
    opts.pack(fill="x", padx=16)
    ttk.Checkbutton(opts, text="РЇСЂР»С‹Рє РЅР° СЂР°Р±РѕС‡РµРј СЃС‚РѕР»Рµ", variable=desktop_var).pack(anchor="w")
    ttk.Checkbutton(opts, text="РЇСЂР»С‹Рє РІ РјРµРЅСЋ В«РџСѓСЃРєВ»", variable=menu_var).pack(anchor="w")
    ttk.Checkbutton(opts, text="РЎСЂР°Р·Сѓ СЃРєР°С‡Р°С‚СЊ HLAE Рё Source 2 Viewer (~150 РњР‘, РЅСѓР¶РµРЅ РёРЅС‚РµСЂРЅРµС‚)",
                    variable=tools_var).pack(anchor="w")
    ttk.Checkbutton(opts, text="Р—Р°РїСѓСЃС‚РёС‚СЊ РїРѕСЃР»Рµ СѓСЃС‚Р°РЅРѕРІРєРё", variable=launch_var).pack(anchor="w")

    # packed from the bottom up, so the buttons can never be pushed out of the window
    buttons = ttk.Frame(root)
    buttons.pack(side="bottom", fill="x", padx=16, pady=12)
    install_btn = ttk.Button(buttons, text="РЈСЃС‚Р°РЅРѕРІРёС‚СЊ")
    install_btn.pack(side="right")
    ttk.Button(buttons, text="РћС‚РјРµРЅР°", command=root.destroy).pack(side="right", padx=6)

    status = tk.StringVar(value="")
    ttk.Label(root, textvariable=status).pack(side="bottom", anchor="w", padx=16)

    bar = ttk.Progressbar(root, mode="determinate", maximum=100.0)
    bar.pack(side="bottom", fill="x", padx=16, pady=(12, 4))

    def do_install():
        install_btn.config(state="disabled")

        def progress(fraction, name):
            bar["value"] = fraction * 100
            status.set(f"РєРѕРїРёСЂРѕРІР°РЅРёРµ: {name}")
            root.update()

        try:
            dest = install(target_var.get(), desktop_var.get(), menu_var.get(), progress)
        except Exception as exc:
            install_btn.config(state="normal")
            status.set("")
            messagebox.showerror("РЈСЃС‚Р°РЅРѕРІРєР° РЅРµ СѓРґР°Р»Р°СЃСЊ", str(exc))
            return
        bar["value"] = 100
        tools_note = ""
        if tools_var.get():
            bar.config(mode="indeterminate")
            bar.start(12)
            status.set("СЃРєР°С‡РёРІР°РЅРёРµ HLAE Рё Source 2 Viewer...")
            root.update()

            def tool_status(line):
                status.set(line)
                root.update()

            got = download_tools(dest, tool_status)
            bar.stop()
            bar.config(mode="determinate")
            bar["value"] = 100
            tools_note = ("\n\nHLAE Рё Source 2 Viewer СЃРєР°С‡Р°РЅС‹ вЂ” РїСЂРѕРіСЂР°РјРјР° РіРѕС‚РѕРІР° Рє СЂР°Р±РѕС‚Рµ."
                          if got else
                          "\n\nРРЅСЃС‚СЂСѓРјРµРЅС‚С‹ СЃРєР°С‡Р°С‚СЊ РЅРµ СѓРґР°Р»РѕСЃСЊ (РЅРµС‚ СЃРµС‚Рё?) вЂ” РїСЂРѕРіСЂР°РјРјР° "
                          "РґРѕРєР°С‡Р°РµС‚ РёС… РїСЂРё РїРµСЂРІРѕРј РёСЃРїРѕР»СЊР·РѕРІР°РЅРёРё.")
        status.set(f"Р“РѕС‚РѕРІРѕ: {dest}")
        messagebox.showinfo("РЈСЃС‚Р°РЅРѕРІРєР° Р·Р°РІРµСЂС€РµРЅР°",
                            f"{APP} СѓСЃС‚Р°РЅРѕРІР»РµРЅ РІ\n{dest}\n\n"
                            "cs2toUE.exe вЂ” РѕРєРЅРѕ РїСЂРѕРіСЂР°РјРјС‹\n"
                            "cs2toue-cli.exe вЂ” С‚Рѕ Р¶Рµ СЃР°РјРѕРµ РІ РєРѕРЅСЃРѕР»Рё" + tools_note)
        if launch_var.get():
            os.startfile(str(dest / "cs2toUE.exe"))
        root.destroy()

    install_btn.config(command=do_install)

    # size the window to what the content actually needs, then center it
    root.update_idletasks()
    width = max(640, root.winfo_reqwidth())
    height = root.winfo_reqheight()
    x = max(0, (root.winfo_screenwidth() - width) // 2)
    y = max(0, (root.winfo_screenheight() - height) // 3)
    root.geometry(f"{width}x{height}+{x}+{y}")
    root.minsize(width, height)
    root.resizable(True, False)
    root.mainloop()


def say(text: str) -> None:
    """The installer is a windowed exe, so stdout can be missing entirely."""
    try:
        if sys.stdout is not None:
            sys.stdout.write(text + "\n")
            sys.stdout.flush()
    except Exception:
        pass


def run_silent(argv):
    target = default_target()
    shortcuts = True
    tools = True
    log = None
    for i, arg in enumerate(argv):
        if arg.startswith("--target="):
            target = Path(arg.split("=", 1)[1])
        elif arg == "--target" and i + 1 < len(argv):
            target = Path(argv[i + 1])
        elif arg == "--no-shortcuts":
            shortcuts = False
        elif arg == "--no-tools":
            tools = False
        elif arg.startswith("--log="):
            log = Path(arg.split("=", 1)[1])
    say(f"installing to {target}")
    try:
        dest = install(target, shortcuts, shortcuts)
    except Exception as exc:
        say(f"failed: {exc}")
        if log:
            log.write_text(f"failed: {exc}\n", encoding="utf-8")
        return 1
    result = f"installed: {dest}"
    if tools:
        say("downloading HLAE and Source 2 Viewer")
        got = download_tools(dest, say)
        result += "\ntools: " + ("downloaded" if got else "not downloaded, will be fetched later")
    say(result)
    if log:
        log.write_text(result + "\n", encoding="utf-8")
    return 0


def force_utf8() -> None:
    """Make output readable no matter what code page the machine uses."""
    os.environ.setdefault("PYTHONUTF8", "1")
    for stream in (sys.stdout, sys.stderr):
        try:
            if stream is not None:
                stream.reconfigure(encoding="utf-8", errors="replace")
        except Exception:
            pass
    try:
        import ctypes
        ctypes.windll.kernel32.SetConsoleOutputCP(65001)
        ctypes.windll.kernel32.SetConsoleCP(65001)
    except Exception:
        pass


def main():
    force_utf8()
    argv = sys.argv[1:]
    if "--silent" in argv or "/S" in argv:
        return run_silent(argv)
    run_gui()
    return 0


if __name__ == "__main__":
    sys.exit(main())
