"""Download, unpack and launch any HLAE build.

Several HLAE versions live side by side under <workspace>/hlae/<version>/, so a demo
from 2023 and a demo from today can each get the build they need.
"""

from __future__ import annotations

import shutil
import zipfile
from pathlib import Path

from ..util import Fail, download, info, ok, warn
from . import index as hlae_index


def version_dir(cfg, version: str) -> Path:
    return cfg.hlae_dir / version


def find_exe(root: Path) -> Path | None:
    exe = root / "HLAE.exe"
    if exe.is_file():
        return exe
    hits = sorted(root.rglob("HLAE.exe"))
    return hits[0] if hits else None


def hook_dll(root: Path, name: str = "AfxHookSource2.dll") -> Path | None:
    for sub in ("x64", "", "bin"):
        cand = root / sub / name if sub else root / name
        if cand.is_file():
            return cand
    hits = sorted(root.rglob(name))
    return hits[0] if hits else None


def installed(cfg) -> list:
    if not cfg.hlae_dir.is_dir():
        return []
    out = []
    for d in sorted(cfg.hlae_dir.iterdir()):
        if d.is_dir() and find_exe(d):
            out.append(d.name)
    return out


def is_installed(cfg, version: str) -> bool:
    return find_exe(version_dir(cfg, version)) is not None


def install(cfg, version: str, force: bool = False) -> Path:
    entry = hlae_index.get(version)
    if not entry:
        raise Fail(f"HLAE {version} not found in the index - run: cs2toue hlae refresh")
    dest = version_dir(cfg, entry["version"])
    if find_exe(dest) and not force:
        info(f"HLAE {entry['version']} already installed at {dest}")
        return dest
    cfg.ensure_dirs()
    zip_path = cfg.downloads_dir / entry["zip_name"]
    if not zip_path.is_file() or zip_path.stat().st_size != entry["zip_size"] or force:
        info(f"downloading HLAE {entry['version']} ({entry['published']})")
        download(entry["zip_url"], zip_path, entry["zip_size"])
    if dest.exists():
        shutil.rmtree(dest, ignore_errors=True)
    dest.mkdir(parents=True, exist_ok=True)
    info(f"extracting to {dest}")
    with zipfile.ZipFile(zip_path) as zf:
        zf.extractall(dest)
    # some release zips wrap everything into a single top level folder
    if not (dest / "HLAE.exe").is_file():
        subdirs = [p for p in dest.iterdir() if p.is_dir()]
        files = [p for p in dest.iterdir() if p.is_file()]
        if len(subdirs) == 1 and not files:
            inner = subdirs[0]
            for item in list(inner.iterdir()):
                shutil.move(str(item), str(dest / item.name))
            inner.rmdir()
    if not find_exe(dest):
        raise Fail(f"HLAE.exe not found after extracting {zip_path.name}")
    ok(f"HLAE {entry['version']} ready: {dest}")
    return dest


def remove(cfg, version: str) -> None:
    d = version_dir(cfg, version)
    if d.is_dir():
        shutil.rmtree(d, ignore_errors=True)
        ok(f"removed {d}")


# ------------------------------------------------------------------ launching

def cfg_dir_for(cfg) -> Path:
    """Where to drop a generated .cfg the game can exec."""
    if cfg.mmcfg:
        d = Path(cfg.mmcfg) / "csgo" / "cfg"
    else:
        from .. import steam
        root = steam.game_root(cfg.cs2_exe)
        if not root:
            raise Fail("cs2_exe is not configured - run: cs2toue setup")
        d = root / "game" / "csgo" / "cfg"
    d.mkdir(parents=True, exist_ok=True)
    return d


def write_session_cfg(cfg, demo_path: str, extra_cmds: list | None = None,
                      name: str = "cs2toue_session") -> Path:
    """Generate the cfg the game runs on start (avoids quoting hell on the cmd line)."""
    lines = [
        "// generated by cs2toUE - do not edit, it is overwritten on every run",
        "// add your own commands with: cs2toue play <demo> --exec \"mirv_...\"",
        f'playdemo "{Path(demo_path).resolve().as_posix()}"',
    ]
    lines += list(extra_cmds or [])
    path = cfg_dir_for(cfg) / f"{name}.cfg"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def build_launch_args(cfg, version: str, demo_path: str = "", hook: str = "AfxHookSource2.dll",
                      width: int = 1920, height: int = 1080, fullscreen: bool = False,
                      extra_game_args: str = "", exec_cfg: str = "") -> list:
    root = version_dir(cfg, version)
    exe = find_exe(root)
    if not exe:
        raise Fail(f"HLAE {version} is not installed - run: cs2toue hlae install {version}")
    dll = hook_dll(root, hook)
    if not dll:
        raise Fail(f"{hook} not found inside {root}")
    if not cfg.cs2_exe:
        raise Fail("cs2_exe is not configured - run: cs2toue setup")

    from .. import steam
    game_cmd = ["-steam", "-insecure", "-console"]
    game_cmd.append("-full" if fullscreen else "-sw")
    game_cmd += ["-w", str(width), "-h", str(height)]
    if cfg.mmcfg:
        game_cmd.append("-afxDisableSteamStorage")
    if exec_cfg:
        game_cmd.append(f"+exec {exec_cfg}")
    elif demo_path:
        game_cmd.append(f'+playdemo "{Path(demo_path).resolve().as_posix()}"')
    if extra_game_args:
        game_cmd.append(extra_game_args)

    sp = cfg.steam_path or steam.steam_path()
    args = [
        str(exe), "-customLoader", "-noGui", "-autoStart",
        "-hookDllPath", str(dll),
        "-programPath", str(cfg.cs2_exe),
        "-cmdLine", " ".join(game_cmd),
    ]
    # cs2.exe launched outside Steam needs these, exactly like the HLAE CS2 launcher does
    for env in (f"SteamPath={sp}", "SteamClientLaunch=1", "SteamGameId=730",
                "SteamAppId=730", "SteamOverlayGameId=730"):
        args += ["-addEnv", env]
    if cfg.mmcfg:
        args += ["-addEnv", f"USRLOCALCSGO={cfg.mmcfg}"]
    if not sp:
        warn("Steam path unknown; cs2.exe may refuse to start")
    return args
